# Generated by Django 4.1.1 on 2022-09-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stportal', '0002_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
