# Generated by Django 4.1.1 on 2022-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stportal', '0003_applicationmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='app_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
